### ISSUE TITLE
load and Save data to leaderboard.json 

### ISSUE THREAD

**Issue by Anirban-Majumder** [legosiv/valiant-valkyries#47]

**Comment by jalwn** [comment]
I created a new branch save_to_json_file_ng

check the implementation of save_score_ng

at this stage game has already ended, user press save, `{"user": "someone", "score": 200}` gets sent to server.

then load the leaderboard file to dict, append the value and dump to file again. apply sorting logic before dumping and sending to client.

With this logic, no need to read file before starting the server. only after game ends.

you can fetch the branch and work on it locally `git fetch origin branch_name` then `git switch origin branch_name`, then push after working on it, double check on the commands i might be wrong

use debugger to view data inside variables and which functions get called, this can help you a lot. 

create the a new launch.config file from the debugger view, select fast-api as the debug config option,  replace the file content with what is [here](https://github.com/legosiv/valiant-valkyries/wiki/launch.config-vscode-debugger-for-fastapi), then press run button in the debugger view. Make breakpoints and play the game. server will pause on breakpoints.
