### ISSUE TITLE
Add A real  `It's not a bug, it's a feature`  feature

### ISSUE THREAD

**Issue by Anirban-Majumder** [legosiv/valiant-valkyries#50]
Similar to the famous Nuclear Gandhi bug in Civilization II, we can introduce:

**Bug:** If the snake gets too long, its length inverts and its *head* is now at the *end* of its body (instead of the tail being at the end).

**Feature:** This feature of moving "head-last" allows the rest of the snake's body to overflow through the canvas, thus it easier to handle and it the player will have an easy time staying alive.

If we include some signs and references to [Integer Overflow](https://en.wikipedia.org/wiki/Integer_overflow) and [Nuclear Gandhi](https://en.wikipedia.org/wiki/Nuclear_Gandhi) it can add to the game design.

_Originally posted by @Sushant-Padha in https://github.com/legosiv/valiant-valkyries/issues/13#issuecomment-1198464187_

**Comment by Anirban-Majumder** [comment]
Todo:
after the snake getting long
1. switch the head and tail images
2. change collision detection so the user only loses when the snakes entire body is outside not just the "front"

**Comment by jalwn** [comment]
We could have each one design their own bug, we introduce a timer/event, when event gets triggered a random buggish feature occurs.
