### ISSUE TITLE
Control keystrokes captured even after the game ends

### ISSUE THREAD

**Issue by Sushant-Padha** [legosiv/valiant-valkyries#51]
The `onkeydown` method captures keystrokes including arrow keys and W, A, S, D keys even after the game ends.

**Comment by anirbanmajumder0** [comment]
just click on the username box

**Comment by Sushant-Padha** [comment]
i tested it.
i can not type w, a, s, d characters

**Comment by Sushant-Padha** [comment]
I have fixed it; pushing it now.

**Comment by anirbanmajumder0** [comment]
ohhh i seee
