### ISSUE TITLE
Suggest better logic for food spawn 

### ISSUE THREAD

**Issue by Anirban-Majumder** [legosiv/valiant-valkyries#55]
see main.py line121
you can use score(time playing the game in ms) and snake_size
and difficulty(time in ms when the snake_size-=1 in your logic 
dont use snake_pos 

and also take the variables use in logic as function args

**Comment by Sushant-Padha** [comment]
We can specify a `min_score` and `rarity` for each food type.

When the score is the food type's recorded `min_score`, then it will start spawning.
The spawn rate will be inversely proportional to its `rarity`, i.e., if `rarity` food should get spawned less often.

**Comment by Anirban-Majumder** [comment]
okay sound good
