### ISSUE TITLE
Make the UI Pretty 

### ISSUE THREAD

**Issue by Anirban-Majumder** [legosiv/valiant-valkyries#6]
add canvas/background image 
add snakehead body tail image
add bugs image
change BLOCK_SIZE
try to animate the snake by filping the image
same with the bugs
align everything in a proper way

**Comment by Anirban-Majumder** [comment]
also add a high score table and fill it with dummy data

**Comment by Sushant-Padha** [comment]
> add canvas/background image add snakehead body tail image add bugs image change BLOCK_SIZE try to animate the snake by filping the image same with the bugs align everything in a proper way

I am working on this.
