### ISSUE TITLE
Implement snake tail and different foods

### ISSUE THREAD

**Issue by Sushant-Padha** [legosiv/valiant-valkyries#65]
Snake tail should be a seperate object with a different image.

The different foods should have different behaviour (can be added later), different spawn rates and different images.

Related to issues #61, #60, #56, #55.

**Comment by anirbanmajumder0** [comment]
curcurrently there are 4 food_types
0 = reduce_difficulty food
1 = 4hp food
2 = tigger bugfeature food
3 = hp food

**Comment by anirbanmajumder0** [comment]
closed with implement feature bug
