### ISSUE TITLE
Host the Game somewhere

### ISSUE THREAD

**Issue by Anirban-Majumder** [legosiv/valiant-valkyries#76]

**Comment by Anirban-Majumder** [comment]
like heroku / or something similar

**Comment by jalwn** [comment]
do we have to host before today?

**Comment by Anirban-Majumder** [comment]
i dont know

**Comment by Anirban-Majumder** [comment]
but i would be better if we host i think

**Comment by jalwn** [comment]
![Screenshot_20220731-124450.jpg](https://user-images.githubusercontent.com/85926950/182015596-69cf082b-16dd-4ade-939d-41e193f6ac44.jpg)

I think we can host it later

**Comment by Anirban-Majumder** [comment]
Okay i thought we needed to host.
Close #76
